---

 - hosts: aws-pizza 
   tasks: 
   - name: Update Code in home dir
     git: 
       repo: https://github.com/oniseijin/pizza-luvrs
       dest: "/home/{{ ansible_user }}/pizza-luvrs"
   - name: npm install
     command: npm install
     args: 
       chdir: "/home/{{ ansible_user }}/pizza-luvrs"
  
  